const ADD_TO_CART = 'ADD_TO_CART'

const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

const EMPTY_CART = 'EMPTY_CART'

const SEND_CART = 'SEND_CART'

export { ADD_TO_CART, REMOVE_FROM_CART, EMPTY_CART, SEND_CART }
